channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  - pip=22.1.2
  - nodejs=14.15.4

rccPostInstall:
  - rfbrowser init

- pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==15.6.0 # https://rpaframework.org/releasenotes.html
    - robotframework-browser==11.1.0